services:
  - type: web
    name: pan-afrik-redis
    runtime: node
    plan: free
    region: frankfurt
    healthCheckPath: /health
    envVars:
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: panafrik-redis
          property: internalConnectionString
      - key: JWT_SECRET
        sync: false
      - key: EXCHANGE_RATE_API_KEY
        sync: false
      - key: NODE_ENV
        value: production
